# Generated by Django 5.2.17 on 2026-09-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('quantity', models.FloatField(help_text='Quantity in kilograms')),
                ('pickup_address', models.CharField(max_length=255)),
                ('available_until', models.DateTimeField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('CLAIMED', 'Claimed'), ('COLLECTED', 'Collected'), ('EXPIRED', 'Expired')], default='AVAILABLE', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
